version: '2'

services:
  php:
    user: "${UID}:${GID}"
    build: ./
    container_name: php8
    ports: 
      - 80:80
    volumes:
      - ./project:/var/www/html/ecommerce
      - ./conf/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - m2dev
      
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ecomadmin
      MYSQL_DATABASE: ecommerce
    networks:
      - m2dev

  elasticsearch:
    image: elasticsearch:7.17.7
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"
    depends_on:
      - db
      - php
    networks:
      - m2dev

  phpmyadmin:
    image: phpmyadmin
    links: 
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
networks:
  m2dev: