version: '2'

services:
  php:
    build: ./
    ports: 
      - 80:80
    volumes:
      - ./project:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ecomadmin
      MYSQL_DATABASE: ecommerce

  elasticsearch:
    image: elasticsearch:7.17.7
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"

  phpmyadmin:
    image: phpmyadmin
    links: 
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:8025