<?php
/**
 * @var \Xclm2\Cafe\Block\Adminhtml\Order $block
 */
$collection = $block->getActiveOrders();
if ($collection->count()) {
?>
<style>
#orders-table {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#orders-table td, #orders-table th {
  border: 1px solid #ddd;
  padding: 8px;
}

#orders-table tr:nth-child(even){background-color: #f2f2f2;}

#orders-table tr:hover {background-color: #ddd;}

#orders-table th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #04AA6D;
  color: white;
}
#served{
    background-color: #98EFAB;
    border-color: #98EFAB;
}
#preparing{
    background-color: #85CCD0;
    border-color: #85CCD0;
}
</style>
<div class="table-wrapper orders-customers">
    <table class="data table table-order-items customers" id="orders-table">
        <thead>
        <tr>
            <th scope="col" class="col img"><?php echo __('') ?></th>
            <th scope="col" class="col table"><?php echo __('Table') ?></th>
            <th scope="col" class="col email"><?php echo __('Item') ?></th>
            <th scope="col" class="col addons"><?php echo __('Add-ons') ?></th>
            <th scope="col" class="col cancel"><?php echo __('Control') ?></th>
            <th scope="col" class="col createat"><?php echo __('Created At') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php
 foreach ($collection as $item): ?>
        <tr>
            <td data-th="<?= $block->escapeHtml(__('img')) ?>" class="col img">
                <img src="<?= $block->getImageUrl($item->getProductId()) ?>" name="product_image">
            </td>
            <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                <?= $item->getTableCode() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Menu')) ?>" class="col menu">
                <?= $item->getName() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Add-ons')) ?>" class="col addons">
                <?= $item->getAddOns() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Control')) ?>" class="col status" data-status="<?= $item->getItemStatus() ?>" data-item-id="<?= $item->getItemId() ?>">
                <button class="btn primary preparing" data-value="preparing">Preparing</button>
                <button class="btn default served" data-value="served">Served</button>
                <button class="btn action-secondary cancel" data-value="cancelled">Cancel</button>
                <p><?= $item->getItemId() ?> <br><?= $block->escapeHtml(__($item->getItemStatus())) ?></p>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Created At')) ?>"
                class="col title"><?php echo date('Y-m-d', strtotime($item->getCreatedAt())); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
}
?>
<script>
    require(['jquery'], function($){
        var statuscss = {
            "preparing": {'background-color': 'rgb(133, 204, 208, 0.5)'},
            "served": {'background-color': 'rgb(152, 239, 171, 0.5)'},
            "cancel": {'background-color': 'rgb(81, 73, 67, 0.5)'}
        }
        setTimeout(function(){
            $('.col.status').each(function(){
                var item_status = $(this).attr('data-status');
                $(this).parent().css(statuscss[item_status]);
            })
        }, 1000);
        $('.btn.preparing,.btn.served,.btn.cancel').on('click', function(){
            var status = $(this).attr('data-value'),
                item_id = $(this).parent().attr('data-item-id');
            // $.ajax({
            //     'url'
            // });
            var params = {
                status: status,
                item_id: item_id
            }
            console.log(params);
            $(this).parent().parent().css(statuscss[status]);
            $.ajax({
                url: "<?= $block->updateItemUrl() ?>",
                dataType: "JSON",
                data: params,
                type: 'post',
                success: function(response){
                    console.log(response);
                },
                error: function(response){
                    console.log(response);
                }
            })
        });
    });
</script>