<?php 
/**
 * @var \Techxspace\Cafe\Block\Dine $block
 */
?>
<style>
.dine-container {
    width:50%;
}
</style>
<div class="dine-container">
    <form class="form form-dine" action="<?= $block->escapeHtml($block->getSaveUrl()) ?>" method="post" id="form-validate">
        <input name="form_key" type="hidden" value="<?= $block->escapeHtml($block->getFormKey()) ?>" />

        <fieldset class="fieldset dine" data-hasrequired="* Required Fields">
            <div class="field firstname required">
                <label class="label" for="firstname" data-role="firstname-label">
                    <span>First Name</span>
                </label>
                <div class="control">
                    <input id="firstname" type="text" name="firstname" value="" 
                        placeholder="Firstname" 
                        class="input-text required-entry" 
                        data-validate="{required:true}"
                        aria-expanded="false">
                </div>
            </div>
            <div class="field lastname required">
                <label class="label" for="lastname" data-role="lastname-label">
                    <span>Lastname</span>
                </label>
                <div class="control">
                    <input id="lastname" type="text" name="lastname" value="" 
                        placeholder="Lastname" 
                        class="input-text required-entry" 
                        data-validate="{required:true}"
                        aria-expanded="false">
                </div>
            </div>
            <div class="field email">
                <label class="label" for="email" data-role="email-label">
                    <span>Email</span>
                </label>
                <div class="control">
                    <input id="email" type="text" name="email" value="" 
                        placeholder="Email" 
                        class="input-text" 
                        data-validate="{email:true}"
                        aria-expanded="false">
                </div>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action login primary" name="send" id="send2">
                        <span>Submit</span>
                    </button>
                </div>
            </div>
        </fieldset>
    </form>
    <a href="<?= $block->getUrl('customer/account/login') ?>">Already have an account?</a>
</div>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        }
    }
</script>